name: Build and Push Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y Subir Imagen del Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          # Etiqueta la imagen con "latest" y con el número de tu Release (ej. v1.0.0)
          tags: |
            ghcr.io/dp1-6f-pucp/dp1-frontend:latest
            ghcr.io/dp1-6f-pucp/dp1-frontend:${{ github.event.release.tag_name }}

      - name: Construir y Subir Imagen del Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/dp1-6f-pucp/dp1-backend:latest
            ghcr.io/dp1-6f-pucp/dp1-backend:${{ github.event.release.tag_name }}
